sudo: required
language: node_js
services:
  - docker

# Build docker image
before_install:
  - cd WebShopClient
  - docker build -t thaulow/webshopclient .

# Run tests
# script:
  # - docker run thaulow/webshopclient npm run test -- --browsers ChromeHeadlessNoSandbox --watch=false