sudo: required
# Install Node
language: node_js
node_js:
  - "10"

# Make Docker available
services:
  - docker

 # Install Chrome 
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - cd WebShopClient
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

# Install dependencies  
before_script:
- npm install

script: 
- npm run test -- --browsers ChromeHeadlessNoSandbox --watch=false
# - npm run e2e

# Build docker image
after_success:
  - cd WebShopClient
  - docker build -t thaulow/webshopclient .
  # Run tests
  - docker run thaulow/webshopclient npm run test -- --browsers ChromeHeadlessNoSandbox --watch=false
  