version: "3"
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
    depends_on:
      - client
  # api:
  #   build:
  #     context: WebShopServer/WebShop
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./WebShopServer/WebShop:/app
  client:
    build:
      context: WebShopClient
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./WebShopClient:/app
