version: "3"
services:
  # backend:
  #   build:
  #     context: WebShopServer
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5000:5000"
  #     - "5001:5001"
  client:
    build:
      context: WebShopClient
      dockerfile: Dockerfile
    ports:
      - "4200:4200"